# Header
menu:
  HOME: https://www.maoushimazu.tk
  RESUME: https://www.maoushimazu.tk/resume/
  ABOUT: https://www.maoushimazu.tk/#about

# banner
banner: https://www.maoushimazu.tk/assets/img/header.jpg

# notice text
notice: My Github https://github.com/Maou-Shimazu

# profile config
author:
  name: Maou Shimazu
  avatar: https://www.maoushimazu.tk/assets/img/yoru.jpg
  description: Stay Lean and Code.

toc:
  max_depth: 3
  min_depth: 2 

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  valine:
    appId: 
    appKey: 
    avatar: mm
    placeholder: 
    notify: true
    visitor: true
    pageSize: 10
  # docs: https://disqus.com/
  disqus:
    website: 
    error: diquis error

# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

beian: 

google_analytics: 
gauges_analytics:
baidu_analytics: 
tencent_analytics: 
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    github  : https://github.com/Maou-Shimazu/